---
title: "A comparison of sad playlists"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readr)
library(lubridate)
library(ggplot2)
library(tidyverse)
library(spotifyr)

urgh <- get_playlist_audio_features('', '3zHgInxVVBHhge5rc71TBk?si=fbb92d3bd6134cbb')
nostalgia <- get_playlist_audio_features('', '6WjvDxvrtZHQO0I4sjhWcG?si=bf12bda2f6444809')
spelen <- get_playlist_audio_features('', '75aP68kX1ZjvXTLFmwAn1N?si=f94ac20a680343ac')

sad_lists <- rbind(urgh, nostalgia, spelen)
```

Corpus
===================================== 

text {data-width=500}
-----------------------------------------------------------------------

What do people listen to when they feel down?

On spotify you will find many playlist with 'music to cry your heart out to' or 'sad songs', music to soothe or to swoon in. I think it would be very interesting to compare two of these playlists and see what the recurring characteristics are, or that maybe different people have very different musical needs when they feel down. The comparison point herein will probably be in the ambience, tempo and chords of the music.
These two playlists will be very subjective and probably differ much depending on the creators that are chosen. Because of this, it could be hard to generalize the answer to this question.

Plots
===================================== 

Plot 1 {data-width=500}
-----------------------------------------------------------------------


```{r}
plot1 <- ggplot(sad_lists, aes(x = playlist_name, y = valence)) + geom_violin()

plot1
```

Plot 2 {data-width=500}
-----------------------------------------------------------------------

```{r}
plot2 <- ggplot(sad_lists, aes(x = tempo, y = loudness, size = valence)) + geom_point() + facet_wrap(~playlist_name)

plot2
```